/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * avito-tech-assignment-winter-2025-server-swagger 🚀
 * OpenAPI spec version: 1.0.0
 */
export type ItemsType = (typeof ItemsType)[keyof typeof ItemsType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemsType = {
    Недвижимость: 'Недвижимость',
    Авто: 'Авто',
    Услуги: 'Услуги',
} as const

export interface Items {
    id: string
    name: string
    description: string
    location: string
    type: ItemsType
    image?: string
    propertyType?: string
    area?: number
    rooms?: number
    price?: number
    brand?: string
    model?: string
    year?: number
    mileage?: number
    serviceType?: string
    experience?: number
    cost?: number
    workSchedule?: string
}

export interface Params {
    id: string
}

export type GetItemsId404 = {
    error: string
}
