/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * avito-tech-assignment-winter-2025-server-swagger 🚀
 * OpenAPI spec version: 1.0.0
 */
export type RealEstateSchemaType = (typeof RealEstateSchemaType)[keyof typeof RealEstateSchemaType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealEstateSchemaType = {
    REAL_ESTATE: 'REAL_ESTATE',
} as const

export interface RealEstateSchema {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: RealEstateSchemaType
    /** @minLength 1 */
    propertyType: string
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    area: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    rooms: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    price: number
}

export type CarSchemaType = (typeof CarSchemaType)[keyof typeof CarSchemaType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CarSchemaType = {
    AUTO: 'AUTO',
} as const

export interface CarSchema {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: CarSchemaType
    /** @minLength 1 */
    brand: string
    /** @minLength 1 */
    model: string
    /** @minimum 1886 */
    year: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    mileage: number
}

export type ServiceSchemaType = (typeof ServiceSchemaType)[keyof typeof ServiceSchemaType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceSchemaType = {
    SERVICES: 'SERVICES',
} as const

export interface ServiceSchema {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: ServiceSchemaType
    /** @minLength 1 */
    serviceType: string
    /** @minimum 0 */
    experience: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    cost: number
    workSchedule?: string
}

export type FormSchemaAnyOfType = (typeof FormSchemaAnyOfType)[keyof typeof FormSchemaAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormSchemaAnyOfType = {
    REAL_ESTATE: 'REAL_ESTATE',
} as const

export type FormSchemaAnyOf = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: FormSchemaAnyOfType
    /** @minLength 1 */
    propertyType: string
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    area: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    rooms: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    price: number
}

export type FormSchemaAnyOfThreeType = (typeof FormSchemaAnyOfThreeType)[keyof typeof FormSchemaAnyOfThreeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormSchemaAnyOfThreeType = {
    AUTO: 'AUTO',
} as const

export type FormSchemaAnyOfThree = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: FormSchemaAnyOfThreeType
    /** @minLength 1 */
    brand: string
    /** @minLength 1 */
    model: string
    /** @minimum 1886 */
    year: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    mileage: number
}

export type FormSchemaAnyOfFiveType = (typeof FormSchemaAnyOfFiveType)[keyof typeof FormSchemaAnyOfFiveType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormSchemaAnyOfFiveType = {
    SERVICES: 'SERVICES',
} as const

export type FormSchemaAnyOfFive = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: FormSchemaAnyOfFiveType
    /** @minLength 1 */
    serviceType: string
    /** @minimum 0 */
    experience: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    cost: number
    workSchedule?: string
}

export type FormSchema = FormSchemaAnyOf | FormSchemaAnyOfThree | FormSchemaAnyOfFive

export type PostItemsBodyAnyOfType = (typeof PostItemsBodyAnyOfType)[keyof typeof PostItemsBodyAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostItemsBodyAnyOfType = {
    REAL_ESTATE: 'REAL_ESTATE',
} as const

export type PostItemsBodyAnyOf = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: PostItemsBodyAnyOfType
    /** @minLength 1 */
    propertyType: string
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    area: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    rooms: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    price: number
}

export type PostItemsBodyAnyOfThreeType = (typeof PostItemsBodyAnyOfThreeType)[keyof typeof PostItemsBodyAnyOfThreeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostItemsBodyAnyOfThreeType = {
    AUTO: 'AUTO',
} as const

export type PostItemsBodyAnyOfThree = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: PostItemsBodyAnyOfThreeType
    /** @minLength 1 */
    brand: string
    /** @minLength 1 */
    model: string
    /** @minimum 1886 */
    year: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    mileage: number
}

export type PostItemsBodyAnyOfFiveType = (typeof PostItemsBodyAnyOfFiveType)[keyof typeof PostItemsBodyAnyOfFiveType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostItemsBodyAnyOfFiveType = {
    SERVICES: 'SERVICES',
} as const

export type PostItemsBodyAnyOfFive = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: PostItemsBodyAnyOfFiveType
    /** @minLength 1 */
    serviceType: string
    /** @minimum 0 */
    experience: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    cost: number
    workSchedule?: string
}

export type PostItemsBody = PostItemsBodyAnyOf | PostItemsBodyAnyOfThree | PostItemsBodyAnyOfFive

export type GetItems200ItemAnyOfType = (typeof GetItems200ItemAnyOfType)[keyof typeof GetItems200ItemAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetItems200ItemAnyOfType = {
    REAL_ESTATE: 'REAL_ESTATE',
} as const

export type GetItems200ItemAnyOf = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: GetItems200ItemAnyOfType
    /** @minLength 1 */
    propertyType: string
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    area: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    rooms: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    price: number
}

export type GetItems200ItemAnyOfThreeType =
    (typeof GetItems200ItemAnyOfThreeType)[keyof typeof GetItems200ItemAnyOfThreeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetItems200ItemAnyOfThreeType = {
    AUTO: 'AUTO',
} as const

export type GetItems200ItemAnyOfThree = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: GetItems200ItemAnyOfThreeType
    /** @minLength 1 */
    brand: string
    /** @minLength 1 */
    model: string
    /** @minimum 1886 */
    year: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    mileage: number
}

export type GetItems200ItemAnyOfFiveType =
    (typeof GetItems200ItemAnyOfFiveType)[keyof typeof GetItems200ItemAnyOfFiveType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetItems200ItemAnyOfFiveType = {
    SERVICES: 'SERVICES',
} as const

export type GetItems200ItemAnyOfFive = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: GetItems200ItemAnyOfFiveType
    /** @minLength 1 */
    serviceType: string
    /** @minimum 0 */
    experience: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    cost: number
    workSchedule?: string
}

export type GetItems200Item = GetItems200ItemAnyOf | GetItems200ItemAnyOfThree | GetItems200ItemAnyOfFive

export type GetItemsId200AnyOfType = (typeof GetItemsId200AnyOfType)[keyof typeof GetItemsId200AnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetItemsId200AnyOfType = {
    REAL_ESTATE: 'REAL_ESTATE',
} as const

export type GetItemsId200AnyOf = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: GetItemsId200AnyOfType
    /** @minLength 1 */
    propertyType: string
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    area: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    rooms: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    price: number
}

export type GetItemsId200AnyOfThreeType = (typeof GetItemsId200AnyOfThreeType)[keyof typeof GetItemsId200AnyOfThreeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetItemsId200AnyOfThreeType = {
    AUTO: 'AUTO',
} as const

export type GetItemsId200AnyOfThree = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: GetItemsId200AnyOfThreeType
    /** @minLength 1 */
    brand: string
    /** @minLength 1 */
    model: string
    /** @minimum 1886 */
    year: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    mileage: number
}

export type GetItemsId200AnyOfFiveType = (typeof GetItemsId200AnyOfFiveType)[keyof typeof GetItemsId200AnyOfFiveType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetItemsId200AnyOfFiveType = {
    SERVICES: 'SERVICES',
} as const

export type GetItemsId200AnyOfFive = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: GetItemsId200AnyOfFiveType
    /** @minLength 1 */
    serviceType: string
    /** @minimum 0 */
    experience: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    cost: number
    workSchedule?: string
}

export type GetItemsId200 = GetItemsId200AnyOf | GetItemsId200AnyOfThree | GetItemsId200AnyOfFive

export type PutItemsIdBodyAnyOfType = (typeof PutItemsIdBodyAnyOfType)[keyof typeof PutItemsIdBodyAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutItemsIdBodyAnyOfType = {
    REAL_ESTATE: 'REAL_ESTATE',
} as const

export type PutItemsIdBodyAnyOf = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: PutItemsIdBodyAnyOfType
    /** @minLength 1 */
    propertyType: string
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    area: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    rooms: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    price: number
}

export type PutItemsIdBodyAnyOfThreeType =
    (typeof PutItemsIdBodyAnyOfThreeType)[keyof typeof PutItemsIdBodyAnyOfThreeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutItemsIdBodyAnyOfThreeType = {
    AUTO: 'AUTO',
} as const

export type PutItemsIdBodyAnyOfThree = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: PutItemsIdBodyAnyOfThreeType
    /** @minLength 1 */
    brand: string
    /** @minLength 1 */
    model: string
    /** @minimum 1886 */
    year: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    mileage: number
}

export type PutItemsIdBodyAnyOfFiveType = (typeof PutItemsIdBodyAnyOfFiveType)[keyof typeof PutItemsIdBodyAnyOfFiveType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutItemsIdBodyAnyOfFiveType = {
    SERVICES: 'SERVICES',
} as const

export type PutItemsIdBodyAnyOfFive = {
    /**
     * @minLength 21
     * @maxLength 21
     * @pattern ^[a-zA-Z0-9_-]{21}$
     */
    id?: string
    /** @minLength 1 */
    name: string
    /** @minLength 1 */
    description: string
    /** @minLength 1 */
    location: string
    photo?: string
    type: PutItemsIdBodyAnyOfFiveType
    /** @minLength 1 */
    serviceType: string
    /** @minimum 0 */
    experience: number
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    cost: number
    workSchedule?: string
}

export type PutItemsIdBody = PutItemsIdBodyAnyOf | PutItemsIdBodyAnyOfThree | PutItemsIdBodyAnyOfFive
